name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: elenakrittik/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: elenakrittik
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Minsk
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_habits: yes
          plugin_habits_languages_limit: 8
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_languages: yes
          plugin_languages_ignored: yacc, procfile, cmake
